#Generated viper config file. Changes should be made in cmd/root.go
#This file will be overwritten by viper if there are changes. Left it here for development purposes.
api_service_base_url: http://api.devportal.name
