// Code generated by MockGen. DO NOT EDIT.
// Source: ./clients/api_client.go

// Package mock_clients is a generated GoMock package.
package clients

import (
gomock "github.com/golang/mock/gomock"
reflect "reflect"
)

// MockRestClient is a mock of RestClient interface
type MockRestClient struct {
	ctrl     *gomock.Controller
	recorder *MockRestClientMockRecorder
}

// MockRestClientMockRecorder is the mock recorder for MockRestClient
type MockRestClientMockRecorder struct {
	mock *MockRestClient
}

// NewMockRestClient creates a new mock instance
func NewMockRestClient(ctrl *gomock.Controller) *MockRestClient {
	mock := &MockRestClient{ctrl: ctrl}
	mock.recorder = &MockRestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRestClient) EXPECT() *MockRestClientMockRecorder {
	return m.recorder
}

// GetHello mocks base method
func (m *MockRestClient) GetHello() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHello")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHello indicates an expected call of GetHello
func (mr *MockRestClientMockRecorder) GetHello() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHello", reflect.TypeOf((*MockRestClient)(nil).GetHello))
}