version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: go run main.go

  test:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: go test ./...

  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: secrethub run --env-file secrethub.env -- /bin/sh -eo pipefail
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          context: dps-va-di
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/