version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0

executors:
  go-agent:
    docker:
      - image: cimg/go:1.15.2
  node-agent:
    docker:
      - image: cimg/node:14.13.1

jobs:
  build:
    executor: go-agent
    steps:
      - checkout
      - run: go run main.go

  test:
    executor: go-agent
    steps:
      - checkout
      - run: go test ./...

  tag:
    executor: node-agent
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token-rich
    steps:
      - checkout
      - secrethub/exec:
          command: |
            sudo npm install -g semver@5.5.0
            current_version=$(git describe --abbrev=0 | tr -d 'v')
            new_version=$(semver -c -i patch $current_version)
            echo $new_version
            git config --global user.email "rilau@thoughtworks.com"
            git config --global user.name "Rich Lau"
            git tag -a $new_version -m "${new_version}"
            git push origin master "v${new_version}"

  release:
    executor: go-agent
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - secrethub/exec:
          step-name: Publish Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          context: dps-va-di
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - tag:
          context: dps-va-di