version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0

executors:
  go-agent:
    docker:
      - image: cimg/go:1.15.2

jobs:
  build:
    executor: go-agent
    steps:
      - checkout
      - run: go run main.go

  test:
    executor: go-agent
    steps:
      - checkout
      - run: go test ./...

  tag:
    machine: true
    steps:
      - checkout
      - run: docker run --rm alpine/semver semver -c -i minor 1.0.2