version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: go run main.go

  test:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: go test ./...

workflows:
  build_and_test:
    jobs:
      - build
      - test