version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0

executors:
  go-agent:
    docker:
      - image: cimg/go:1.15.2

jobs:
  check-for-secrets:
    executor: go-agent
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - secrethub/exec:
          step-name: Run
          command: |
            curl -sL https://raw.githubusercontent.com/awslabs/git-secrets/master/git-secrets >> git-secrets
            chmod +x git-secrets
            ./git-secrets --add-provider -- cat curl -H "Authorization: token $GITHUB_TOKEN" https://raw.githubusercontent.com/ThoughtWorks-DPS/poc-documentation/master/git-secrets-pattern.txt
            ./git-secrets --scan

  build:
    executor: go-agent
    steps:
      - checkout
      - run: go run main.go

  test:
    executor: go-agent
    steps:
      - checkout
      - run: go test ./...

  tag:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "48:34:f1:e3:cb:c7:fa:40:cc:70:9f:62:f4:95:10:cb"
      - run: |
          current_version=$(git describe --abbrev=0 | tr -d 'v')
          new_version=$(docker run --rm alpine/semver semver -c -i patch $current_version)
          git config --global user.email "rilau@thoughtworks.com"
          git config --global user.name "Rich Lau"
          git tag -a "v${new_version}" -m "v${new_version}"
          git push origin master "v${new_version}"

  release:
    executor: go-agent
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - secrethub/exec:
          step-name: Publish Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - check-for-secrets
      - build
      - test
      - hold:
          type: approval
          requires:
            - check-for-secrets
            - build
            - test
      - tag:
          requires:
            - hold
      - release:
          context: dps-va-di
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/