version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: go run main.go

  test:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: go test ./...

  release:
    docker:
      - image: cimg/go:1.15.2
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  publish_release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*