version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0

executors:
  go-agent:
    docker:
      - image: cimg/go:1.15.2

jobs:
  build:
    executor: go-agent
    steps:
      - checkout
      - run: go run main.go

  test:
    executor: go-agent
    steps:
      - checkout
      - run: go test ./...

  tag:
    machine: true
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - secrethub/exec:
          command: curl -sL https://git.io/goreleaser | bash

  release:
    executor: go-agent
    environment:
      GITHUB_TOKEN: secrethub://vapoc/platform/svc/github/access-token
    steps:
      - checkout
      - secrethub/exec:
          step-name: Publish Release
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - tag
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          context: dps-va-di
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/